name = "cf-drive"
compatibility_date = "2025-02-10"

[vars]
SITE_NAME = "CF Simple Drive"
CHUNK_SIZE = 26214400
MAX_CHUNKS_PER_FILE = 20
MAX_KV_TOTAL_SIZE_MB = 1000
BLOCKED_EXTENSIONS = "exe,bat,cmd,sh,com,pif,scr,vbs"
DEFAULT_FILE_PRIVATE = true
AUTO_COMPRESS = true

[[d1_databases]]
binding = "DB"
database_name = "drive-db"
database_id = "cb30476a-696d-4cb9-ad76-19d71f9f5d0d"

[[kv_namespaces]]
binding = "KV"
id = "d9e8c8ab14c9429b9db73ce5f3f5c65c"
